channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pandas>=2.2.0
  - numpy>=2.0.0
  - r-base=4.3
  - r-tidyverse
  - r-vroom
  - r-readxl
  - r-jsonlite
  - r-data.table
  - r-caret
  - r-rlist
  - r-reticulate
  - bioconductor-deseq2
  - bioconductor-mofa2
